export { HomePage } from './HomePage'
export { AboutPage } from './AboutPage'
export { SettingsPage } from './SettingsPage'
export { MachineIdPage } from './MachineIdPage'
export { KiroSettingsPage } from './KiroSettingsPage'
export { AutoRegisterPage } from './AutoRegisterPage'
export { ChangePasswordPage } from './ChangePasswordPage'
export { VaultPage } from './VaultPage'
